### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hijiangtao** [hijiangtao/rainmood#2]
较明确的功能规划

* [x] 点击 Logo 切换歌曲 <https://github.com/hijiangtao/rainmood/commit/654dc1f72e292e288646f137ced6f391759e216e>
* [x] 单曲循环功能 <https://github.com/hijiangtao/rainmood/commit/9a106680fee20efa9e351da6161cc390a42d76a7>
* [ ] 自定义音乐资源地址
* [x] 自定义音量大小 <https://github.com/hijiangtao/rainmood/commit/9a106680fee20efa9e351da6161cc390a42d76a7>

**Comment by hijiangtao** [comment]
自定义音乐资源地址暂不实现
